Report remaining chars
nolanlawson/pinafore pull request #2300
Opened 2022-12-05 14:58 UTC by nvdaes

2022-12-05 15:00 UTC, nvdaes commented
Fixes issue #2267

2022-12-09 16:29 UTC, nolanlawson commented on src/routes/_components/LengthIndicator.html
> +          return 'polite'
Now that `intl.overLimit` and `intl.underLimit` are unused, we can remove them from `en-US.js` (and the other intl files in the same directory).

2022-12-09 16:30 UTC, nolanlawson commented on src/routes/_components/LengthIndicator.html
> +      lengthVerbosity: ({ lengthToDisplayDeferred }) => {
```suggestion
      lengthVerbosity: ({ lengthToDisplayDeferred }) => {
        // When approaching the limit, notify screen reader users
```

2022-12-09 16:32 UTC, nolanlawson approved these changes

2022-12-09 16:35 UTC, nolanlawson commented on src/routes/_components/LengthIndicator.html
> +        if (lengthToDisplayDeferred > WARN_THRESHOLD) {
```suggestion
        if (lengthToDisplayDeferred > WARN_THRESHOLD || lengthToDisplayDeferred <= 0) {
```

@nvdaes It seems to me that we should keep warning if the user reaches 0 or goes beyond the limit (-1, -2, etc.). Let me know what you think of this change. :arrow_up:

2022-12-09 16:35 UTC, nolanlawson requested changes
See question above, otherwise LGTM

2022-12-09 16:39 UTC, nolanlawson approved these changes

2022-12-09 16:59 UTC, nvdaes commented
Thanks @nolanlawson. Several times I had to rewrite a toot since I exceeded the limit of characters and this may help a lot when we type a long message

2022-12-10 18:40 UTC, merged